---
name: Hello
on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v4
      - name: prints hello
        run: echo "Hello from github actions"
      - name: prints date and time
        run: date
      - name: prints the name of the branch
        run: echo "The triggered branch name is ${{ github.ref_name }}"
      - name: listing the files in the repo
        run: ls -la
      - name: Print os name of the runner
        run: echo "The operating system is $RUNNER_OS"    
