---
name: Hello
on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v4
      - name: prints hello
        run: echo "Hello from github actions"
