---
name: Schedule
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  schedule-job:
    runs-on: unbuntu-latest
    steps:
      - name: run a scheduled script
        run: echo "this job runs on a schedule at midnight UTC everyday"
